### ISSUE TITLE
Consider updating `symengine` pin

### ISSUE THREAD

**Issue by bharat-thotakura** [Infleqtion/client-superstaq#1080]
### What is happening?

We currently pin `symengine~=0.11.0` after https://github.com/Infleqtion/client-superstaq/pull/874 in the requirements of `qiskit-superstaq`. However, that version seems to have issues building a wheel in a Python 3.13 environment, so we should pin the recently released `v0.13.0` which installs as expected (and since `qiskit>=1.0.0` supports `symengine>=0.11`).

### Any additional context?
qiskit-superstaq version: 0.5.27
qiskit version: 1.2.2
Python version: 3.13.0rc2
Operating system: Ubuntu

**Comment by bharat-thotakura** [comment]
Related: https://github.com/Qiskit/qiskit/pull/13251

**Comment by jakelishman** [comment]
Also Qiskit/qiskit#13259 - we borked the 1.2.3 release by being in too much of a rush, and yanked it.  We'll make 1.2.4 shortly (tomorrow, most likely), which should be ok for any combination of symengine 0.11 and 0.13 between client and server, since `ParameterExpression` should limit our exposure to the full set of changes in symengine between those versions.

We hadn't come across the problem before, but it looks like you guys did in #874.  We'll be working on reducing our dependence on `symengine` in the future.  Near-term, we're hoping to cut it out of serialisation (Qiskit/qiskit#13252), and longer term, _potentially_ remove the dependence entirely.

**Comment by vtomole** [comment]
@natibek Run a basic submission locally after updating this pin to make sure roundtrip serialization works.

**Comment by natibek** [comment]
Closed with #1097
