### ISSUE TITLE
notes on QCVV library

### ISSUE THREAD

**Issue by richrines1** [Infleqtion/client-superstaq#1092]
i've spent a bit of time recently approaching our qcvv library as a user. High level reaction: it's really quite nice, and genuinely makes life easier when implementing/experimenting with qcvv routines. Using this space to collect a few notes on things i things i didn't quite love/found a bit cumbersome

## separation of responsibilities:
the biggest inconvenience for me was that lack of separation between experiment definition and experimental results. For example, if i want to do a sensitivity analysis by simulating the same experiment with varying noise parameters, currently i have to either instantiate a new experiment and regenerate all the circuits using the same random seed, or overwrite the results of the previous run every time. To circumvent this i found myself reaching for `deepcopy()` a few times

imo experiment construction and results should be separated as much as possible (for example probabilities probably don't belong in the sample class?)

#### proposal:
maybe the current experiment classes should each actually be \*two\* classes: an "experiment" class, containing the circuit generation/compilation logic and the various `run_with_<x>` methods, and a `result` class (similar to `cirq.experiments.RandomizedBenchmarkResult`) containing the job retrieval, analysis, and plotting routines. The `run_with_<x>` methods should return new instances of the result class without altering the experiment class/samples. these results objects could include a reference to the experiment class that generated them, so they'd have access to the samples/etc for analysis

this would make it super easy to run sensitivity analyses (i'd just reuse `run_with..` for each configuration). it also would make it easy to e.g. run an experiment on both a simulator and a device, or submit the same experiment to multiple devices for comparison

added bonus: it would also obviate the "overwrite" logic in various methods

#### another thought:
haven't really thought this through fully but it seems like the result class could maybe even subclass `css.Job`? then we'd get all the status checking/refreshing logic for free..

## workflow:
* it's a little confusing (and easy to forget) that we have to run both `collect_results` and `analyze_results`, especially after a running with a local simulator
* similarly (though much less significant) - it's also a little confusing why `prepare_experiment` isn't part of the initializer - there doesn't seem to be any case in which i wouldn't want to call it exactly once, immediately after instantiating the experiment

#### proposal:
maybe we should make this behave similarly to how job results are handled, e.g.:
* change `collect_results()` into a private `_refresh()` method
* provide a non-blocking `.status()` method, which internally would call `_refresh()` iff the results haven't already been already collected, and then return the current status to the user
* have `analyze_results` block until `status()` returns a terminal status (just like `css.Job.counts()`)

this would give users the option to avoid any blocking calls (by checking `.status()` before calling `.analyze_circuits()`), but would also make the extra call unnecessary if we know it's already in a terminal state (such as for a local simulation job)

## minor notes:
* it'd be nice if error messages were more specific about what needs to be run - e.g. currently `.samples` will raise "No samples to retrieve. The experiment has not been run.", but it'd be more helpful if it just told me to run `.prepare_experiment()` (this may be somewhat obviated by other suggestions)
* there should be a way to disable the progressbars in methods that use them
* it'd also be nice if the `run_with_callable` method was a little more flexible in terms of counts (e.g. accepting integers as keys instead of strings)

**Comment by cdbf1** [comment]
I agree with splitting up the experiment and the results objects so that the `experiment.run_with<x>()` function effectively becomes a factory for `Results` objects.

I'm not quite so keen on subclassing `css.Job` for because it will require users to have a `css.Service` set up and it will probably be quite fiddly to integrate results from a local simulator. Instead i suggest that the results objects have a `job` attribute which stores the `css.Job` associated with the results. That way it is a small wrapper function to check if the results are ready but the user can still interogate the full results object as desired (but now we have a single job object for each results object rather than associating jobs with samples as we had before.

I've made a start at implementing these changes (see [#1095](https://github.com/Infleqtion/client-superstaq/pull/1095)). Its not actually too involved to move things around although I haven't yet fixed the tests or updated the docs. Could you have a look at the example notebooks on the branch and see if the revised interface is more along the lines of what you were looking for? If so I'll finish off the docs/tests and get a PR submitted :)
