### ISSUE TITLE
Don't hardcode `backend.configuration()`

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#342]
Related: https://github.com/SupertechLabs/superstaq-client/issues/150 https://github.com/SupertechLabs/superstaq-client/issues/151

**Comment by dowusu-antwi** [comment]
IIRC, this issue is about parity with `qiskit` so `qiskit`-familiar users like Colin won't experience whiplash, i.e.,
```python
provider = qss.SuperstaqProvider()
hilbert = provider.get_backend("cq_hilbert_qpu")
hilbert.configuration().n_qubits  # gets number of qubits
hilbert.configuration().max_experiments  # gets maximum number of experiments
```
The server-side [`backend_info` issue](https://github.com/Infleqtion/server-superstaq/issues/1116) arose independently to assemble useful device info, possibly including info `qiskit_backend.configuration` does not (e.g., perhaps from `qiskit_backend.properties`)  -- but it looks like that won't be the case, so repurposing `target_info` to populate a client-side version of [`BackendConfiguration`](https://qiskit.org/documentation/stubs/qiskit.providers.models.BackendConfiguration.html) should fix #342.

In retrospect, also having `target_info` makes sense b/c it's a much cleaner representation (particularly for non-qiskit-familiar users, but also in general).

**Comment by stephanielee9** [comment]
Related: https://github.com/Infleqtion/client-superstaq/issues/151, https://github.com/Infleqtion/client-superstaq/issues/150

**Comment by vtomole** [comment]
Started a draft PR in https://github.com/Infleqtion/client-superstaq/pull/666 but it's requiring too many mocks. Thinking about how to accomplish this with less lines of code.

**Comment by vtomole** [comment]
Done by https://github.com/Infleqtion/client-superstaq/pull/666
