### ISSUE TITLE
Update IBM tutorial files

### ISSUE THREAD

**Issue by stephanielee9** [Infleqtion/client-superstaq#464]

**Comment by knsmith** [comment]
@dowusu-antwi post discussion, current understanding for this issue is to add text to [ibmq_compile_css.ipynb](https://github.com/SupertechLabs/client-superstaq/blob/main/docs/source/optimizations/ibm/ibmq_compile_css.ipynb) and [ibmq_compile_qss.ipynb](https://github.com/SupertechLabs/client-superstaq/blob/main/docs/source/optimizations/ibm/ibmq_compile_qss.ipynb) to get users up and running. 

In the future, a notebook containing unit tests that show superstaq advantage over qiskit optimization would be helpful. Small scale circuits would be for "advanced" users, and "example user tests" would have ~5 lines of code that show outstanding benefits w/ superstaq. These would serve as the first examples that superstaq users would try 

- Applications w/ DD, pulse level optimizations, SWAP optimizations, etc 
- Circuit fidelity, program duration as figures of merit

**Comment by knsmith** [comment]
@bharat-thotakura
