### ISSUE TITLE
`css` doesn't warn about missing AQT configs

### ISSUE THREAD

**Issue by dowusu-antwi** [Infleqtion/client-superstaq#594]
### What is happening?

`css` doesn't give a warning about missing AQT configs.

### How can we reproduce the issue?

```python
import qiskit_superstaq as qss
provider = qss.SuperstaqProvider()
circuit = ...
provider.get_backend("aqt_keysight_qpu").compile(circuit)  # shows a warning about qtrl configs

import cirq_superstaq as css
service = css.Service()
circuit = ...
service.compile(circuit, target="aqt_keysight_qpu")  # no warning
```

### What should happen?

For parity, both clients should throw the warning.

### Environment

- **Superstaq version**: 0.4.0
- **general-superstaq version**: 0.4.0
- **cirq-superstaq version**: 0.4.0
- **qiskit-superstaq version**: 0.4.0
- **Operating system**: Ubuntu 22.04.2
- **Python version**: 3.9

### Any additional context?

None.

**Comment by richrines1** [comment]
this was an intentional change: see https://github.com/Infleqtion/server-superstaq/pull/2293

**Comment by dowusu-antwi** [comment]
Also, for `qss` it says `service.upload_aqt_configs` instead of `provider.upload_aqt_configs`:
![image](https://github.com/Infleqtion/client-superstaq/assets/18367737/59794f2d-828b-4656-8ba2-da53e04da6cc)

**Comment by richrines1** [comment]
just noticed - the problem is just that you're using `service.compile()` instead of `service.aqt_compile()` for css, which doesn't call `read_json_aqt` (and so wouldn't give you a pulse sequence even if you did have configs). We should probably just fix this so that `css.Service.compile()` calls `aqt_compile`/`qscout_compile`/etc just like `qss.SuperstaqBackend.compile()`
