### ISSUE TITLE
Integration tests run when `exclude` argument is passed into the coverage check

### ISSUE THREAD

**Issue by vtomole** [Infleqtion/client-superstaq#697]
The `*_integration_test.py` files should not be running in `Pytest and Coverage check`. There could be a bug in our checks that makes them run when the `exclude` argument is passed.

**Comment by cjguttormsson** [comment]
I don't know that there's anything we need to do here, this is just a consequence of how default args work: since we went from using a default arg with a non-empty value to providing that arg explicitly, we won't get the default anymore.

If this is something we think should work differently, then the general coverage_.py file could be updated to add `*_integration_test.py` to whatever other values were passed in, but that would honestly be a lot of complication (particularly due to the fact that the type of the argument is either a string or a sequence of strings, so there's extra heterogeneity to deal with).

**Comment by vtomole** [comment]
^^ Good point. Closing.
