### ISSUE TITLE
Job cancellation not implemented

### ISSUE THREAD

**Issue by ColinCampbellCQ** [Infleqtion/client-superstaq#822]
### What is happening?

Trying to cancel a job raises a NotImplementedError
![image](https://github.com/Infleqtion/client-superstaq/assets/108485140/7a8eaaea-6810-4f40-8cf7-b70e0f7495e5)

**Comment by stephanielee9** [comment]
@vtomole (or perhaps @ColinCampbellCQ), by Oct 31, can you either:
* complete work to close this issue (if a week is enough time), or
* comment in this issue 1) the plan of action to close this issue, 2) a rough timeline of when you expect that work to be done, and 3) assign this issue

**Comment by vtomole** [comment]
@ColinCampbellCQ  Will work on this.

**Comment by ColinCampbellCQ** [comment]
I have no idea how to do this.
The best I could think of was for a CQJob on the server side to add
```
def cancel(self):
     self._job.cancel()
```
but I don't even know where to start for other types of backends or what needs to be done on the client side

**Comment by stephanielee9** [comment]
@richrines1 to type up resolution / plan for closing this issue

**Comment by stephanielee9** [comment]
@richrines1 Wanted to check if you'd still be able to type up a plan for closing this issue this week?

**Comment by richrines1** [comment]
possible steps to fixing:
1. define a generic `SuperstaqJob.cancel(options)` method in superstaq/job.py (which should do nothing)
2. define `**Job.cancel(options)` methods in any vendor-specific `SuperstaqJob` subclasses which support job cancellation (e.g. `AzureJob`, `CQJob`)
    * `job.cancel()` should probably always check `job.get_status()` before doing anything, and only cancel the job if it's not already in a terminal state
    * for cq and ibm jobs, the `options` dictionary will need to be handled in the same way it is in `job.to_dict` (it might contain credentials necessary to access the job). i don't think it will need to be used in any of the other subclasses
3. add a `/cancel_jobs` endpoint to web/server.py, which will look very similar to `/fetch_jobs` but will call `job.cancel()` on the expanded jobs instead of `job.to_dict()`
4. define `gss._SuperstaqClient.cancel_jobs()` to reach the new endpoint (will look very similar to `_SuperstaqJob.fetch_jobs()`)
5. add `cancel()` methods to both `qss.SuperstaqJob` and `css.Job`, which will call `_client.cancel_jobs()` with a list of job ids

**Comment by stephanielee9** [comment]
medium priority

**Comment by bharat-thotakura** [comment]
Closing as completed by https://github.com/Infleqtion/client-superstaq/pull/998
